# Generated by Django 2.2 on 2021-08-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210816_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default=False, upload_to=''),
            preserve_default=False,
        ),
    ]
